### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cla7aye15I4nd** [cla7aye15I4nd/awesome-mcu#1]
- [ ] MCU AFL-fuzzer
- [ ] Peripheral interface
  - [x] Serial peripheral interface (SPI)
  - [x] Inter-integrated circuit (I2C)
  - [x] DMA controller (DMA)
  - [x] Real-time clock (RTC)
  - [x] Advanced-control timer / General-purpose timers (TIM)
  - [x] Controller area network (bxCAN)
  - [ ] Random number generator (RNG)
  - [ ] Hash processor (HASH)
  - [ ] Inter-IC Sound (I2S)
  - [ ] External interrupt/event controller (EXTI)
  - [ ] USB on-the-go full-speed (OTG_FS)
  - [ ] Cryptographic processor (CRYP)
  - [ ] USB on-the-go high-speed (OTG_HS)
  - [ ] Analog-to-digital converter (ADC)
  - [ ] Digital-to-analog converter (DAC)
  - [ ] System configuration controller (SYSCFG)
  - [ ] Digital camera interface (DCMI)
  - [ ] Flexible static memory controller (FSMC)
  - [ ] Flexible memory controller (FMC)
- [ ] More Arch
  - [x] Cortex-M
  - [ ] Cortex-A
  - [x] RISCV
- [ ] RTOS / Kernel (https://en.wikipedia.org/wiki/Comparison_of_real-time_operating_systems)
  - [x] FreeRTOS
  - [ ] RT-thread
  - [ ] Liteos-m (Huawei)
  - [ ] Tock OS (Rust)
- [x] MCU project
  - [x] BetaFlight
  - [x] EmuFlight
- [ ] Support of STM series
  - [ ] STM32F1
  - [ ] STM32F2
  - [x] STM32F4
  - [ ] STM32F7
